# This is taken from https://github.com/Area69Lab/Recovery-Builder-NoKernel
# All credits goes to above repo

name: Building recovery

on:
  workflow_dispatch:
  watch:
    types: [started]

env:
  MANIFEST: git://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git
  MANIFEST_BRANCH: twrp-12.1
  DEVICE: RMX2151
  DT_LINK: https://github.com/Gofaraway71/twrp-RMX2151-A12.1
  DT_PATH: device/realme/RMX2151
  TARGET: recoveryimage
  TZ: Asia/Kolkata

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initializing environment
      run: |
        docker rmi `docker images -q` >/dev/null 2>&1
        sudo -E apt-get remove aisleriot brltty duplicity empathy* example-content gnome* landscape-common libreoffice* libsane* python3-uno rhythmbox* sane-utils shotwell* telepathy* totem* printer* >/dev/null 2>&1 
        sudo -E apt-get purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php* >/dev/null 2>&1
        sudo -E apt-get clean >/dev/null 2>&1
        sudo -E apt-get update >/dev/null 2>&1
        sudo -E apt-get install git-core gnupg flex bison build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 libncurses5 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig >/dev/null 2>&1
        sudo -E curl --create-dirs -L -o /usr/local/bin/repo -O -L https://storage.googleapis.com/git-repo-downloads/repo
        sudo -E chmod a+rx /usr/local/bin/repo
        git config --global user.name "Gofaraway71"
        git config --global user.email "aalbatron@gmail.com"
        sudo -E apt-get clean
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install bc build-essential zip curl libstdc++6 git wget python gcc clang libssl-dev repo rsync flex bison aria2
        sudo curl --create-dirs -L -o /usr/local/bin/repo -O -L https://storage.googleapis.com/git-repo-downloads/repo
        sudo chmod a+rx /usr/local/bin/repo

    - name: Sync recovery source and device tree
      run: |
        mkdir work
        cd work
        repo init -u $MANIFEST -b $MANIFEST_BRANCH --depth=1 --groups=all,-notdefault,-device,-darwin,-x86,-mips
        repo sync -j4
        repo sync
        git clone $DT_LINK --depth=1 --single-branch $DT_PATH

    - name: Build
      run: |
        cd work && export ALLOW_MISSING_DEPENDENCIES=true && . build/envsetup.sh && lunch twrp_$DEVICE-eng && mka $TARGET

    - uses: actions/upload-artifact@v2
      with:
          name: recoveryzip
          path: work/out/target/product/*/*.zip

    - uses: actions/upload-artifact@v2
      with:
          name: recoveryimage
          path: work/out/target/product/*/*.img
          
    - name: Upload recovery image
      run: |
        cd work/out/target/product/$DEVICE
        curl -sL https://git.io/file-transfer | sh
        ./transfer wet *.img
        ./transfer wet *.zip
        
